use keli_cli::{
    DEFAULT_CORE_CERTIFICATION_SCHEMA_VERSION, DEFAULT_MANAGED_MIXED_MAX_CONNECTION_WORKERS,
    DOCTOR_REPORT_SCHEMA_VERSION, INTEROP_MATRIX_SCHEMA_VERSION,
    MANAGED_CONNECTION_REPORT_HISTORY_LIMIT, MANAGED_MIXED_RECENT_EVENT_LIMIT,
    MANAGED_MIXED_STATUS_SCHEMA_VERSION, READINESS_CHECK_SCHEMA_VERSION,
    SUPPORT_BUNDLE_SCHEMA_VERSION,
};
use keli_client_core::DEFAULT_RUNTIME_EVENT_HISTORY_LIMIT;
use keli_net_core::DEFAULT_TUN_TCP_MAX_ACTIVE_SESSIONS;

#[test]
fn doctor_report_lists_supported_outbounds() {
    let mut output = Vec::new();
    keli_cli::write_doctor_report(&mut output).expect("write doctor report");
    let output = String::from_utf8(output).expect("doctor utf8");

    assert!(output.contains("version="));
    assert!(output.contains(&format!(
        "schema_versions doctor_report={} support_bundle={} interop_matrix={} readiness_check={} default_core_certification={} managed_mixed_status={}",
        DOCTOR_REPORT_SCHEMA_VERSION,
        SUPPORT_BUNDLE_SCHEMA_VERSION,
        INTEROP_MATRIX_SCHEMA_VERSION,
        READINESS_CHECK_SCHEMA_VERSION,
        DEFAULT_CORE_CERTIFICATION_SCHEMA_VERSION,
        MANAGED_MIXED_STATUS_SCHEMA_VERSION
    )));
    assert!(output.contains("system_proxy_state="));
    assert!(output.contains("tun_device_supported="));
    assert!(output.contains("lifecycle_available="));
    assert!(output.contains("packet_io_available="));
    assert!(output.contains("tun_backend platform=Windows backend=wintun"));
    assert!(output.contains("driver_api_available="));
    assert!(output.contains("lifecycle_wired=true"));
    assert!(output.contains("packet_io_wired=true"));
    assert!(output.contains("route_takeover_wired=true"));
    assert!(output.contains("dns_leak_prevention_policy_available=true"));
    assert!(output.contains("dns_address_family_policy_available=true"));
    assert!(output.contains("dns_default_local_resolution_policy=allow-system"));
    assert!(output.contains("dns_default_address_family_policy=dual-stack"));
    assert!(output.contains(
        "route_rule_capabilities=domain-suffix,domain-keyword,ip-exact,ip-cidr,port-exact,port-range"
    ));
    assert!(output.contains(
        "tun_packet_pipeline_capabilities=ipv4,ipv6,tcp,udp,udp-payload,icmp,route-decision,dns-hijack,dns-query-plan,dns-engine-response,packet-process-action,udp-response-packet,dns-response-packet,ipv4-fragment-guard,ipv6-extension-traversal,ipv6-extension-guard,packet-loop,packet-loop-summary,managed-packet-loop,direct-udp-relay,outbound-udp-relay,registry-udp-relay,managed-registry-udp-relay,listen-mixed-tun-runtime,concurrent-tun-runtime,background-runtime-report,tun-runtime-status-note,packet-io-readiness,tcp-segment-parse,tcp-response-packet,tcp-reset-response,tcp-syn-ack-response,tcp-syn-retransmit-guard,tcp-session-table,tcp-client-payload-ack,tcp-client-duplicate-ack,tcp-client-out-of-order-ack,tcp-client-overlap-ack,tcp-client-stale-server-ack,tcp-client-ack-keepalive,tcp-server-payload-packet,tcp-server-payload-retransmit,tcp-server-payload-ack-clear,tcp-server-mss-read-clamp,tcp-session-step-runner,tcp-session-device-loop,tcp-server-payload-poll,tcp-fin-close-ack,tcp-fin-payload-close,registry-tcp-fin-payload-close,tcp-client-fin-half-close,tcp-client-fin-stale-server-ack,tcp-client-fin-server-payload-retransmit,tcp-client-fin-server-payload-ack-clear,tcp-client-fin-duplicate-poll,tcp-client-fin-duplicate-payload-poll,tcp-client-fin-payload-duplicate-poll,tcp-client-fin-post-close-ack,tcp-client-fin-post-close-payload-ack,tcp-close-sequence-guard,tcp-close-latest-ack-guard,tcp-unknown-session-reset,tcp-server-eof-fin-ack,tcp-server-fin-retransmit,tcp-server-fin-final-ack,tcp-server-fin-client-fin-ack,tcp-server-fin-post-close-guard,tcp-session-idle-cleanup,tcp-close-marker-prune-summary,registry-tcp-session-relay,combined-tun-relay-loop,managed-registry-tcp-session-relay,tcp-relay-plan-summary,relay-plan,tun-runtime-last-error-note,tcp-close-marker-rst-clear,tcp-close-marker-rst-summary,tcp-session-state-summary,tcp-session-state-peak,tcp-session-limit,tcp-session-limit-config,tun-runtime-exit-reason,tun-runtime-exit-reason-label,tun-runtime-structured-diagnostic"
    ));
    assert!(output.contains(
        "stability_diagnostic_capabilities=local-mixed-soak,loopback-echo,managed-metrics,worker-drain,socks5,http-connect,min-duration"
    ));
    assert!(output.contains(
        "interop_matrix_capabilities=protocol-summary,transport-coverage,tcp-relay,udp-relay,profile-source,profile-validation,registry-validation,support-bundle-export"
    ));
    assert!(output.contains(
        "readiness_check_capabilities=doctor-schema,interop-matrix,local-mixed-soak,resource-limits,tun-preflight,system-proxy,panel-subscription-state,support-diagnostics,json-gates,blocker-summary,soak-min-duration,tun-preflight-evidence,tun-runtime-smoke,tun-runtime-smoke-min-duration,tun-runtime-smoke-clean-stop,tun-runtime-smoke-residual-state,tun-runtime-smoke-traffic-stimulus,tun-runtime-smoke-route-takeover-snapshot"
    ));
    assert!(output.contains(
        "tun_backend_check_capabilities=backend-kind,driver-library-detection,driver-api-load,install-required,lifecycle-wiring,packet-io-wiring,route-takeover-wiring,searched-paths,readiness-blocker-detail,validated-runtime-install,package-dir-source,install-plan"
    ));
    assert!(output.contains(
        "default_core_certification_capabilities=schema-version,readiness-embed,tun-backend-evidence,tun-preflight-evidence,tun-runtime-smoke,tun-runtime-smoke-min-duration,tun-runtime-smoke-clean-stop,tun-runtime-smoke-residual-state,tun-runtime-smoke-traffic-stimulus,tun-runtime-smoke-route-takeover-snapshot,non-skipped-soak,soak-parameters,soak-min-duration,promotion-decision,promotion-blockers,json-artifact,text-summary,support-bundle-export"
    ));
    assert!(output.contains(
        "supported_outbounds=direct,socks5-tcp,http-connect,trojan-tcp,trojan-ws,trojan-httpupgrade,trojan-grpc,trojan-h2,trojan-quic,vless-tcp,vless-ws,vless-httpupgrade,vless-grpc,vless-h2,vless-quic,vmess-tcp,vmess-ws,vmess-httpupgrade,vmess-grpc,vmess-h2,vmess-quic,shadowsocks-tcp,anytls-tls-tcp,naive-h2-tcp,naive-h3-quic,mieru-tcp,hy2-quic,tuic-quic"
    ));
    assert!(output.contains(
        "supported_udp_outbounds=direct,socks5-udp,trojan-tcp-udp,trojan-tls-tcp-udp,trojan-ws-udp,trojan-tls-ws-udp,trojan-httpupgrade-udp,trojan-tls-httpupgrade-udp,trojan-grpc-udp,trojan-tls-grpc-udp,trojan-h2-udp,trojan-tls-h2-udp,trojan-quic-udp,vless-tcp-udp,vless-tls-tcp-udp,vless-ws-udp,vless-tls-ws-udp,vless-httpupgrade-udp,vless-tls-httpupgrade-udp,vless-grpc-udp,vless-tls-grpc-udp,vless-h2-udp,vless-tls-h2-udp,vless-quic-udp,vmess-tcp-aead-udp,vmess-tls-tcp-aead-udp,vmess-ws-aead-udp,vmess-tls-ws-aead-udp,vmess-httpupgrade-aead-udp,vmess-tls-httpupgrade-aead-udp,vmess-grpc-aead-udp,vmess-tls-grpc-aead-udp,vmess-h2-aead-udp,vmess-tls-h2-aead-udp,vmess-quic-aead-udp,shadowsocks-aead,anytls-tls-tcp-uot-udp,mieru-tcp-udp,hy2-quic,tuic-quic"
    ));
    assert!(output.contains(
        "protocol_capabilities=trojan=tcp,udp;vless=tcp,udp;vmess=tcp,udp;shadowsocks=tcp,udp;anytls=tcp,udp;naive=tcp;mieru=tcp,udp;hy2=tcp,udp;tuic=tcp,udp;socks=tcp,udp;http=tcp"
    ));
    assert!(output.contains(
        "subscription_fetch_capabilities=http,https,timeout,max-bytes,redacted-source,profile-check-summary"
    ));
    assert!(output.contains(
        "subscription_update_capabilities=current-config,new-config,current-outbound,tag-diff,selected-preservation,default-fallback,redacted-profile-summary,managed-reload-plan,managed-url-reload,managed-url-update-status"
    ));
    assert!(output.contains(
        "managed_connection_metric_capabilities=total-connection-count,success-count,failure-count,connection-limit-rejection-count,error-kind-counts,route-action-counts,inbound-counts,total-upload-bytes,total-download-bytes,total-connect-ms,timed-connect-count,average-connect-ms,total-first-byte-ms,timed-first-byte-count,average-first-byte-ms,last-connection-timestamp,last-success-timestamp,last-failure-timestamp,recent-connection-reports,history-limit"
    ));
    assert!(output.contains(
        "managed_status_schema_capabilities=schema-version,runtime-status,listen-address,selected-outbound,generation,start-time,uptime,connection-metrics,event-count,event-retention,recent-events,runtime-event-diagnostics,last-error,system-proxy,subscription-status,node-health,node-health-coverage,node-health-switch-readiness,node-health-switch-reason,node-health-sweep-diagnostic,node-health-udp-probe,node-health-udp-aware-recommendation,dns-options,tun-tcp-session-limit,connection-worker-counts,panel-state,subscription-url-update-status"
    ));
    assert!(output.contains(&format!(
        "resource_limits runtime_event_history={} managed_status_recent_events={} managed_connection_report_history={} managed_connection_workers={} tun_tcp_max_active_sessions={}",
        DEFAULT_RUNTIME_EVENT_HISTORY_LIMIT,
        MANAGED_MIXED_RECENT_EVENT_LIMIT,
        MANAGED_CONNECTION_REPORT_HISTORY_LIMIT,
        DEFAULT_MANAGED_MIXED_MAX_CONNECTION_WORKERS,
        DEFAULT_TUN_TCP_MAX_ACTIVE_SESSIONS
    )));
}

#[test]
fn doctor_json_report_is_machine_readable() {
    let mut output = Vec::new();
    keli_cli::write_doctor_report_with_format(&mut output, keli_cli::ProbeOutputFormat::Json)
        .expect("write doctor json report");
    let report: serde_json::Value = serde_json::from_slice(&output).expect("doctor json");

    assert_eq!(report["status"], "ok");
    assert_eq!(report["schema_version"], DOCTOR_REPORT_SCHEMA_VERSION);
    assert_eq!(
        report["schema_versions"]["doctor_report"],
        DOCTOR_REPORT_SCHEMA_VERSION
    );
    assert_eq!(
        report["schema_versions"]["support_bundle"],
        SUPPORT_BUNDLE_SCHEMA_VERSION
    );
    assert_eq!(
        report["schema_versions"]["interop_matrix"],
        INTEROP_MATRIX_SCHEMA_VERSION
    );
    assert_eq!(
        report["schema_versions"]["readiness_check"],
        READINESS_CHECK_SCHEMA_VERSION
    );
    assert_eq!(
        report["schema_versions"]["default_core_certification"],
        DEFAULT_CORE_CERTIFICATION_SCHEMA_VERSION
    );
    assert_eq!(
        report["schema_versions"]["managed_mixed_status"],
        MANAGED_MIXED_STATUS_SCHEMA_VERSION
    );
    assert_eq!(report["version"], env!("CARGO_PKG_VERSION"));
    assert_eq!(report["platform"], "Windows");
    assert_eq!(report["system_proxy"]["supported"], true);
    assert_eq!(report["tun"], true);
    assert_eq!(report["tun_device"]["supported"], true);
    assert_eq!(report["tun_device"]["lifecycle_available"], false);
    assert_eq!(report["tun_device"]["packet_io_available"], false);
    assert_eq!(report["tun_device"]["running"], false);
    assert!(report["tun_device"]["interface_name"].is_null());
    assert_eq!(report["tun_backend"]["platform"], "Windows");
    assert_eq!(report["tun_backend"]["backend"], "wintun");
    assert_eq!(report["tun_backend"]["supported"], true);
    assert_eq!(report["tun_backend"]["lifecycle_wired"], true);
    assert_eq!(report["tun_backend"]["packet_io_wired"], true);
    assert_eq!(report["tun_backend"]["route_takeover_wired"], true);
    assert!(report["tun_backend"]["driver_api_available"].is_boolean());
    assert!(
        report["tun_backend"]["driver_api_error"].is_string()
            || report["tun_backend"]["driver_api_error"].is_null()
    );
    assert!(report["tun_backend"]["searched_paths"].is_array());
    assert_eq!(report["inbound"]["kind"], "mixed");
    assert_eq!(report["inbound"]["port"], 7890);
    assert_eq!(report["route_rule_capabilities"][0], "domain-suffix");
    assert_eq!(report["route_rule_capabilities"][3], "ip-cidr");
    assert_eq!(report["tun_packet_pipeline_capabilities"][0], "ipv4");
    assert_eq!(report["tun_packet_pipeline_capabilities"][4], "udp-payload");
    assert_eq!(
        report["tun_packet_pipeline_capabilities"][8],
        "dns-query-plan"
    );
    assert_eq!(
        report["tun_packet_pipeline_capabilities"][9],
        "dns-engine-response"
    );
    assert_eq!(
        report["tun_packet_pipeline_capabilities"][10],
        "packet-process-action"
    );
    assert_eq!(
        report["tun_packet_pipeline_capabilities"][11],
        "udp-response-packet"
    );
    assert_eq!(
        report["tun_packet_pipeline_capabilities"][12],
        "dns-response-packet"
    );
    assert_eq!(
        report["tun_packet_pipeline_capabilities"][13],
        "ipv4-fragment-guard"
    );
    assert_eq!(
        report["tun_packet_pipeline_capabilities"][14],
        "ipv6-extension-traversal"
    );
    assert_eq!(
        report["tun_packet_pipeline_capabilities"][15],
        "ipv6-extension-guard"
    );
    assert_eq!(
        report["tun_packet_pipeline_capabilities"][16],
        "packet-loop"
    );
    assert_eq!(
        report["tun_packet_pipeline_capabilities"][17],
        "packet-loop-summary"
    );
    assert_eq!(
        report["tun_packet_pipeline_capabilities"][18],
        "managed-packet-loop"
    );
    assert_eq!(
        report["tun_packet_pipeline_capabilities"][19],
        "direct-udp-relay"
    );
    assert_eq!(
        report["tun_packet_pipeline_capabilities"][20],
        "outbound-udp-relay"
    );
    assert_eq!(
        report["tun_packet_pipeline_capabilities"][21],
        "registry-udp-relay"
    );
    assert_eq!(
        report["tun_packet_pipeline_capabilities"][22],
        "managed-registry-udp-relay"
    );
    assert_eq!(
        report["tun_packet_pipeline_capabilities"][23],
        "listen-mixed-tun-runtime"
    );
    assert_eq!(
        report["tun_packet_pipeline_capabilities"][24],
        "concurrent-tun-runtime"
    );
    assert_eq!(
        report["tun_packet_pipeline_capabilities"][25],
        "background-runtime-report"
    );
    assert_eq!(
        report["tun_packet_pipeline_capabilities"][26],
        "tun-runtime-status-note"
    );
    assert_eq!(
        report["tun_packet_pipeline_capabilities"][27],
        "packet-io-readiness"
    );
    assert_eq!(
        report["tun_packet_pipeline_capabilities"][28],
        "tcp-segment-parse"
    );
    assert_eq!(
        report["tun_packet_pipeline_capabilities"][29],
        "tcp-response-packet"
    );
    assert_eq!(
        report["tun_packet_pipeline_capabilities"][30],
        "tcp-reset-response"
    );
    assert_eq!(
        report["tun_packet_pipeline_capabilities"][31],
        "tcp-syn-ack-response"
    );
    assert_eq!(
        report["tun_packet_pipeline_capabilities"][32],
        "tcp-syn-retransmit-guard"
    );
    assert_eq!(
        report["tun_packet_pipeline_capabilities"][33],
        "tcp-session-table"
    );
    assert_eq!(
        report["tun_packet_pipeline_capabilities"][34],
        "tcp-client-payload-ack"
    );
    assert_eq!(
        report["tun_packet_pipeline_capabilities"][35],
        "tcp-client-duplicate-ack"
    );
    assert_eq!(
        report["tun_packet_pipeline_capabilities"][36],
        "tcp-client-out-of-order-ack"
    );
    assert_eq!(
        report["tun_packet_pipeline_capabilities"][37],
        "tcp-client-overlap-ack"
    );
    assert_eq!(
        report["tun_packet_pipeline_capabilities"][38],
        "tcp-client-stale-server-ack"
    );
    assert_eq!(
        report["tun_packet_pipeline_capabilities"][39],
        "tcp-client-ack-keepalive"
    );
    assert_eq!(
        report["tun_packet_pipeline_capabilities"][40],
        "tcp-server-payload-packet"
    );
    assert_eq!(
        report["tun_packet_pipeline_capabilities"][41],
        "tcp-server-payload-retransmit"
    );
    assert_eq!(
        report["tun_packet_pipeline_capabilities"][42],
        "tcp-server-payload-ack-clear"
    );
    assert_eq!(
        report["tun_packet_pipeline_capabilities"][43],
        "tcp-server-mss-read-clamp"
    );
    assert_eq!(
        report["tun_packet_pipeline_capabilities"][44],
        "tcp-session-step-runner"
    );
    assert_eq!(
        report["tun_packet_pipeline_capabilities"][45],
        "tcp-session-device-loop"
    );
    assert_eq!(
        report["tun_packet_pipeline_capabilities"][46],
        "tcp-server-payload-poll"
    );
    assert_eq!(
        report["tun_packet_pipeline_capabilities"][47],
        "tcp-fin-close-ack"
    );
    assert_eq!(
        report["tun_packet_pipeline_capabilities"][48],
        "tcp-fin-payload-close"
    );
    assert_eq!(
        report["tun_packet_pipeline_capabilities"][49],
        "registry-tcp-fin-payload-close"
    );
    assert_eq!(
        report["tun_packet_pipeline_capabilities"][50],
        "tcp-client-fin-half-close"
    );
    assert_eq!(
        report["tun_packet_pipeline_capabilities"][51],
        "tcp-client-fin-stale-server-ack"
    );
    assert_eq!(
        report["tun_packet_pipeline_capabilities"][52],
        "tcp-client-fin-server-payload-retransmit"
    );
    assert_eq!(
        report["tun_packet_pipeline_capabilities"][53],
        "tcp-client-fin-server-payload-ack-clear"
    );
    assert_eq!(
        report["tun_packet_pipeline_capabilities"][54],
        "tcp-client-fin-duplicate-poll"
    );
    assert_eq!(
        report["tun_packet_pipeline_capabilities"][55],
        "tcp-client-fin-duplicate-payload-poll"
    );
    assert_eq!(
        report["tun_packet_pipeline_capabilities"][56],
        "tcp-client-fin-payload-duplicate-poll"
    );
    assert_eq!(
        report["tun_packet_pipeline_capabilities"][57],
        "tcp-client-fin-post-close-ack"
    );
    assert_eq!(
        report["tun_packet_pipeline_capabilities"][58],
        "tcp-client-fin-post-close-payload-ack"
    );
    assert_eq!(
        report["tun_packet_pipeline_capabilities"][59],
        "tcp-close-sequence-guard"
    );
    assert_eq!(
        report["tun_packet_pipeline_capabilities"][60],
        "tcp-close-latest-ack-guard"
    );
    assert_eq!(
        report["tun_packet_pipeline_capabilities"][61],
        "tcp-unknown-session-reset"
    );
    assert_eq!(
        report["tun_packet_pipeline_capabilities"][62],
        "tcp-server-eof-fin-ack"
    );
    assert_eq!(
        report["tun_packet_pipeline_capabilities"][63],
        "tcp-server-fin-retransmit"
    );
    assert_eq!(
        report["tun_packet_pipeline_capabilities"][64],
        "tcp-server-fin-final-ack"
    );
    assert_eq!(
        report["tun_packet_pipeline_capabilities"][65],
        "tcp-server-fin-client-fin-ack"
    );
    assert_eq!(
        report["tun_packet_pipeline_capabilities"][66],
        "tcp-server-fin-post-close-guard"
    );
    assert_eq!(
        report["tun_packet_pipeline_capabilities"][67],
        "tcp-session-idle-cleanup"
    );
    assert_eq!(
        report["tun_packet_pipeline_capabilities"][68],
        "tcp-close-marker-prune-summary"
    );
    assert_eq!(
        report["tun_packet_pipeline_capabilities"][69],
        "registry-tcp-session-relay"
    );
    assert_eq!(
        report["tun_packet_pipeline_capabilities"][70],
        "combined-tun-relay-loop"
    );
    assert_eq!(
        report["tun_packet_pipeline_capabilities"][71],
        "managed-registry-tcp-session-relay"
    );
    assert_eq!(
        report["tun_packet_pipeline_capabilities"][72],
        "tcp-relay-plan-summary"
    );
    assert_eq!(report["tun_packet_pipeline_capabilities"][73], "relay-plan");
    assert_eq!(
        report["tun_packet_pipeline_capabilities"][74],
        "tun-runtime-last-error-note"
    );
    assert_eq!(
        report["tun_packet_pipeline_capabilities"][75],
        "tcp-close-marker-rst-clear"
    );
    assert_eq!(
        report["tun_packet_pipeline_capabilities"][76],
        "tcp-close-marker-rst-summary"
    );
    assert_eq!(
        report["tun_packet_pipeline_capabilities"][77],
        "tcp-session-state-summary"
    );
    assert_eq!(
        report["tun_packet_pipeline_capabilities"][78],
        "tcp-session-state-peak"
    );
    assert_eq!(
        report["tun_packet_pipeline_capabilities"][79],
        "tcp-session-limit"
    );
    assert_eq!(
        report["tun_packet_pipeline_capabilities"][80],
        "tcp-session-limit-config"
    );
    assert_eq!(
        report["tun_packet_pipeline_capabilities"][81],
        "tun-runtime-exit-reason"
    );
    assert_eq!(
        report["tun_packet_pipeline_capabilities"][82],
        "tun-runtime-exit-reason-label"
    );
    assert_eq!(
        report["tun_packet_pipeline_capabilities"][83],
        "tun-runtime-structured-diagnostic"
    );
    assert_eq!(report["dns_engine"]["resolver"], "system_resolver");
    assert_eq!(report["dns_engine"]["cache_ttl_seconds"], 60);
    assert_eq!(
        report["dns_engine"]["leak_prevention_policy_available"],
        true
    );
    assert_eq!(
        report["dns_engine"]["address_family_policy_available"],
        true
    );
    assert_eq!(
        report["dns_engine"]["default_local_resolution_policy"],
        "allow-system"
    );
    assert_eq!(
        report["dns_engine"]["default_address_family_policy"],
        "dual-stack"
    );
    assert_eq!(report["supported_outbounds"][0], "direct");
    assert_eq!(report["supported_udp_outbounds"][0], "direct");
    assert_eq!(report["subscription_fetch_capabilities"][0], "http");
    assert_eq!(report["subscription_fetch_capabilities"][1], "https");
    assert_eq!(
        report["subscription_fetch_capabilities"][5],
        "profile-check-summary"
    );
    assert_eq!(
        report["subscription_update_capabilities"][0],
        "current-config"
    );
    assert_eq!(report["subscription_update_capabilities"][3], "tag-diff");
    assert_eq!(
        report["subscription_update_capabilities"][6],
        "redacted-profile-summary"
    );
    assert_eq!(
        report["subscription_update_capabilities"][7],
        "managed-reload-plan"
    );
    assert_eq!(
        report["subscription_update_capabilities"][8],
        "managed-url-reload"
    );
    assert_eq!(
        report["subscription_update_capabilities"][9],
        "managed-url-update-status"
    );
    assert_eq!(
        report["managed_connection_metric_capabilities"][0],
        "total-connection-count"
    );
    assert_eq!(
        report["managed_connection_metric_capabilities"][4],
        "error-kind-counts"
    );
    assert_eq!(
        report["managed_connection_metric_capabilities"][5],
        "route-action-counts"
    );
    assert_eq!(
        report["managed_connection_metric_capabilities"][6],
        "inbound-counts"
    );
    assert_eq!(
        report["managed_connection_metric_capabilities"][19],
        "history-limit"
    );
    assert_eq!(
        report["managed_status_schema_capabilities"][0],
        "schema-version"
    );
    assert_eq!(
        report["managed_status_schema_capabilities"][1],
        "runtime-status"
    );
    assert_eq!(
        report["managed_status_schema_capabilities"][11],
        "runtime-event-diagnostics"
    );
    assert_eq!(
        report["managed_status_schema_capabilities"][14],
        "subscription-status"
    );
    assert_eq!(
        report["managed_status_schema_capabilities"][16],
        "node-health-coverage"
    );
    assert_eq!(
        report["managed_status_schema_capabilities"][17],
        "node-health-switch-readiness"
    );
    assert_eq!(
        report["managed_status_schema_capabilities"][18],
        "node-health-switch-reason"
    );
    assert_eq!(
        report["managed_status_schema_capabilities"][19],
        "node-health-sweep-diagnostic"
    );
    assert_eq!(
        report["managed_status_schema_capabilities"][20],
        "node-health-udp-probe"
    );
    assert_eq!(
        report["managed_status_schema_capabilities"][21],
        "node-health-udp-aware-recommendation"
    );
    assert_eq!(
        report["managed_status_schema_capabilities"][25],
        "panel-state"
    );
    assert_eq!(
        report["managed_status_schema_capabilities"][26],
        "subscription-url-update-status"
    );
    assert_eq!(
        report["stability_diagnostic_capabilities"][0],
        "local-mixed-soak"
    );
    assert_eq!(
        report["stability_diagnostic_capabilities"][2],
        "managed-metrics"
    );
    assert_eq!(
        report["stability_diagnostic_capabilities"][5],
        "http-connect"
    );
    assert_eq!(
        report["stability_diagnostic_capabilities"][6],
        "min-duration"
    );
    assert_eq!(report["interop_matrix_capabilities"][0], "protocol-summary");
    assert_eq!(report["interop_matrix_capabilities"][2], "tcp-relay");
    assert_eq!(
        report["interop_matrix_capabilities"][7],
        "support-bundle-export"
    );
    assert_eq!(report["readiness_check_capabilities"][0], "doctor-schema");
    assert_eq!(report["readiness_check_capabilities"][4], "tun-preflight");
    assert_eq!(report["readiness_check_capabilities"][8], "json-gates");
    assert_eq!(report["readiness_check_capabilities"][9], "blocker-summary");
    assert_eq!(
        report["readiness_check_capabilities"][10],
        "soak-min-duration"
    );
    assert_eq!(
        report["readiness_check_capabilities"][11],
        "tun-preflight-evidence"
    );
    assert_eq!(
        report["readiness_check_capabilities"][12],
        "tun-runtime-smoke"
    );
    assert_eq!(
        report["readiness_check_capabilities"][13],
        "tun-runtime-smoke-min-duration"
    );
    assert_eq!(
        report["readiness_check_capabilities"][14],
        "tun-runtime-smoke-clean-stop"
    );
    assert_eq!(
        report["readiness_check_capabilities"][15],
        "tun-runtime-smoke-residual-state"
    );
    assert_eq!(
        report["readiness_check_capabilities"][16],
        "tun-runtime-smoke-traffic-stimulus"
    );
    assert_eq!(
        report["readiness_check_capabilities"][17],
        "tun-runtime-smoke-route-takeover-snapshot"
    );
    assert_eq!(report["tun_backend_check_capabilities"][0], "backend-kind");
    assert_eq!(
        report["tun_backend_check_capabilities"][2],
        "driver-api-load"
    );
    assert_eq!(
        report["tun_backend_check_capabilities"][6],
        "route-takeover-wiring"
    );
    assert_eq!(
        report["tun_backend_check_capabilities"][8],
        "readiness-blocker-detail"
    );
    assert_eq!(
        report["tun_backend_check_capabilities"][9],
        "validated-runtime-install"
    );
    assert_eq!(
        report["tun_backend_check_capabilities"][10],
        "package-dir-source"
    );
    assert_eq!(report["tun_backend_check_capabilities"][11], "install-plan");
    assert_eq!(
        report["default_core_certification_capabilities"][0],
        "schema-version"
    );
    assert_eq!(
        report["default_core_certification_capabilities"][2],
        "tun-backend-evidence"
    );
    assert_eq!(
        report["default_core_certification_capabilities"][3],
        "tun-preflight-evidence"
    );
    assert_eq!(
        report["default_core_certification_capabilities"][4],
        "tun-runtime-smoke"
    );
    assert_eq!(
        report["default_core_certification_capabilities"][5],
        "tun-runtime-smoke-min-duration"
    );
    assert_eq!(
        report["default_core_certification_capabilities"][6],
        "tun-runtime-smoke-clean-stop"
    );
    assert_eq!(
        report["default_core_certification_capabilities"][7],
        "tun-runtime-smoke-residual-state"
    );
    assert_eq!(
        report["default_core_certification_capabilities"][8],
        "tun-runtime-smoke-traffic-stimulus"
    );
    assert_eq!(
        report["default_core_certification_capabilities"][9],
        "tun-runtime-smoke-route-takeover-snapshot"
    );
    assert_eq!(
        report["default_core_certification_capabilities"][10],
        "non-skipped-soak"
    );
    assert_eq!(
        report["default_core_certification_capabilities"][12],
        "soak-min-duration"
    );
    assert_eq!(
        report["default_core_certification_capabilities"][14],
        "promotion-blockers"
    );
    assert_eq!(
        report["default_core_certification_capabilities"][16],
        "text-summary"
    );
    assert_eq!(
        report["default_core_certification_capabilities"][17],
        "support-bundle-export"
    );
    assert_eq!(
        report["resource_limits"]["runtime_event_history"],
        DEFAULT_RUNTIME_EVENT_HISTORY_LIMIT
    );
    assert_eq!(
        report["resource_limits"]["managed_status_recent_events"],
        MANAGED_MIXED_RECENT_EVENT_LIMIT
    );
    assert_eq!(
        report["resource_limits"]["managed_connection_report_history"],
        MANAGED_CONNECTION_REPORT_HISTORY_LIMIT
    );
    assert_eq!(
        report["resource_limits"]["managed_connection_workers"],
        DEFAULT_MANAGED_MIXED_MAX_CONNECTION_WORKERS
    );
    assert_eq!(
        report["resource_limits"]["tun_tcp_max_active_sessions"],
        DEFAULT_TUN_TCP_MAX_ACTIVE_SESSIONS
    );
    assert_eq!(report["sample_profile_valid"], true);
    assert_eq!(report["initial_phase"], "Idle");
}
